apiVersion: v1
kind: Pod
metadata:
  name: web-flux-pod         # Name of the pod
  labels:
    app: webflux             # Label for identifying your pod
spec:
  containers:
  - name: web-flux-container # Name of the container inside the pod
    image: ganeshrkborde/web-flux-demo:21  # Your Docker image from Docker Hub
    imagePullPolicy: Always   # Always pull latest image when pod starts
    ports:
    - containerPort: 8084     # Port your Spring Boot app listens on