apiVersion: v1
kind: Pod
metadata:
  name: web-flux-demo-pod
  labels:
    app: webflux
spec:
  containers:
  - name: web-flux-container
    image: web-flux-demo:14
    imagePullPolicy: Never
    ports:
      - containerPort: 8088