server.port=8088
spring.application.name=web-flux-demo
spring.r2dbc.url=r2dbc:mysql://localhost:3306/ganeshdb
spring.r2dbc.username=root
spring.r2dbc.password=root

resilience4j.circuitbreaker.instances.taskService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.taskService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.taskService.failureRateThreshold=50


logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty=INFO



